#!/bin/bash

trap "kill 0" SIGINT

tmp_dirs=('800-804' '805-809' '810-814' '815-819' '820-824' '825-829' '830-833')

for i in "${tmp_dirs[@]}"; do
    mkdir -p "$i"
    cd "$i"
    python ../gulp.py \
        ../../Raw_Data/DEEM_330k/CIF/"$i" \
        ../../Raw_Data/GULP/DEEM_330k \
        -l ../DEEM2GULP.d/catlow_mod.lib \
        > ../../Raw_Data/GULP/DEEM_330k/gulp_"$i".log &
    sleep 1
    cd ..
done
wait

rmdir "${tmp_dirs[@]}"

